version: "3.7"

services:
  bot:
    build:
      context: .
    working_dir: /app/
    command: sh -c "alembic upgrade head && cd src && python -m dayz.presentation.bot.main"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always

  db:
    image: postgres:latest
    command: postgres -c 'max_connections=999'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgresql-data-test:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  admin_panel:
    build:
      context: .
    working_dir: /app/src
    command: sh -c "python -m dayz.presentation.admin.main;"
    env_file:
      - .env
    depends_on:
      - db
      - bot
    volumes:
      - .:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: on-failure
    ports:
      - "8100:8100"

  rabbitmq:
    image: rabbitmq:3.10.7-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    restart: always

volumes:
  postgresql-data-test: